### ISSUE TITLE
Is there a roadmap available?

### ISSUE THREAD

**Issue by zp-zpanda** [KubaZ2/NetCord#56]
I've tried using your project and find it promising but I believe that as this project is still in alpha, future users would be deterred. Would it be possible to add a roadmap of sorts, so that users can better understand the objectives and the future of this project? Thanks!

**Comment by Red-K0** [comment]
There's a stable release coming out fairly soon if that's what you're looking for. Tagging @KubaZ2 , they'd have a clearer answer.

**Comment by Red-K0** [comment]
There's a stable release coming out fairly soon if that's what you're looking for. Tagging @KubaZ2, they'd have a clearer answer.

I think a main issue in terms of roadmapping would be that new features or support are usually tied to Discord's API, general performance improvements or QoL updates are usually an 'as-they-come' situation.

Documentation updates soon though.

**Comment by zp-zpanda** [comment]
@Red-K0 thanks for the speedy reply! Looking forward to a stable release!

**Comment by KubaZ2** [comment]
Hi, thanks for trying NetCord out! The main reason NetCord is in alpha stage is breaking changes. I really want NetCord to be perfect for the stable release, because making some bigger changes later would require bumping it to 2.0.0. What is left to do is some rewrites and improvements (currently only VoiceClient and NetCord.Services are known to be left, but it may change anytime), implementing some recently added Discord features and documentation improvements.

**Comment by Red-K0** [comment]
No problem, you should join the Discord server, that's usually where stuff like the stable release is discussed (and support, etc)

**Comment by zp-zpanda** [comment]
Ok, thanks!
